config/routes.rb
Rails.application.routes.draw do
  resources :car_manufacturers, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  resources :fuel_registers, only: [:index, :new, :create, :edit, :update, :destroy, :show]

   get '/home', to: 'home#index'
   get '/brand_models', to: 'brand_models#index'
   get '/fuel_registers', to: 'fuel_registers#index'
   get '/car_manufacturers', to: 'car_manufacturers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_manufacturer.rb
class CarManufacturer < ApplicationRecord

    belongs_to :type_fuel, class_name: 'FuelRegister', foreign_key: 'type_fuel_id'
end

app/models/fuel_register.rb
class FuelRegister < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brand_model_controller.rb
class BrandModelController < ApplicationController
  def index
  end
end

app/controllers/car_manufacturers_controller.rb
class CarManufacturersController < ApplicationController

  before_action :set_car_manufacturer, only: [:show, :edit, :update, :destroy]
  
  def index
    @car_manufacturer = CarManufacturer.all
  end
  
  def new
    @car_manufacturer = CarManufacturer.new
    @fuel_registers = FuelRegister.all
  end

  def show;end

  def edit
    @car_manufacturer = CarManufacturer.find(params[:id])
    @fuel_registers = FuelRegister.all
  end

  def create
    binding.pry
    @car_manufacturer = CarManufacturer.new(car_manufacturer_params)
    @fuel_registers = FuelRegister.all

    respond_to do |format|
      if @car_manufacturer.save
        format.html { redirect_to car_manufacturers_url(@car_manufacturer), notice: "Manufacturer was successfully created." }
        format.json { render :show, status: :created, location: @car_manufacturer }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @car_manufacturer = CarManufacturer.find(params[:id])
    @fuel_registers = FuelRegister.all
    if @car_manufacturer.update(car_manufacturer_params)
      redirect_to @car_manufacturer, notice: 'Car Manufaturer type was succesfully updated.'
    else
      puts @car_manufacturer.errors.full_messages
      render :edit      
    end
  end

  def destroy
    if @car_manufacturer.destroy
  
      respond_to do |format|
        format.html { redirect_to car_manufacturers_url(@car_manufacturer), notice: "Fuel was successfully destroyed." }
        format.json { head :no_content }
        end
      else
        redirect_to car_manufacturers_url, alert: @car_manufacturer.errors.messages[:base][0]
      end
    end

  private

  def set_car_manufacturer
    @car_manufacturer = CarManufacturer.find(params[:id])
  end

  def car_manufacturer_params
  params.require(:car_manufacturer).permit(:manufacturer, :car_model, :year, :capacity, :type_fuel_id, :reported_consumption)
end 
end

app/controllers/fuel_registers_controller.rb
class FuelRegistersController < ApplicationController
  before_action :set_fuel_register, only: [:show, :edit, :update, :destroy]

  def index
    @fuel_register = FuelRegister.all
  end
  def new
    @fuel_register = FuelRegister.new
  end

  def show;end

  def edit
  end

  def create
    @fuel_register = FuelRegister.new(fuel_register_params)

    respond_to do |format|
      if @fuel_register.save
        format.html { redirect_to fuel_registers_url(@fuel_register), notice: "Fuel Type was successfully created." }
        format.json { render :show, status: :created, location: @fuel_register }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @fuel_register.update(fuel_register_params)
      redirect_to @fuel_register, notice: 'Fuel type was succesfully updated.'
    else
      render :edit      
    end
  end

  def destroy
    if @fuel_register.destroy
  
      respond_to do |format|
        format.html { redirect_to fuel_registers_url(@fuel_register), notice: "Fuel was successfully destroyed." }
        format.json { head :no_content }
        end
      else
        redirect_to fuel_registers_url, alert: @fuel_register.errors.messages[:base][0]
      end
    end

  private

def set_fuel_register
    @fuel_register = FuelRegister.find(params[:id])
end

def fuel_register_params
  params.require(:fuel_register).permit(:type_fuel, :value_liter)
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_manufacturer_helper.rb
module CarManufacturerHelper
    def car_manufacturer_form(car_manufacturer)
        render partial: 'car_manufacturer/form', locals: { car_manufacturer: car_manufacturer }
      end
end

app/helpers/fuel_register_helper.rb
module FuelRegisterHelper
    def fuel_register_form(fuel_register)
        render partial: 'fuel_register/form', locals: { fuel_register: fuel_register }
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marca_modelo_helper.rb
module MarcaModeloHelper
end

app/views/brand_model/index.html.erb
<h1>MarcaModelo#index</h1>
<p>Find me in app/views/marca_modelo/index.html.erb</p>

app/views/car_manufacturers/_form.html.erb
<%= form_for(@car_manufacturer) do |f| %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :manufacturer %>
      <%= f.text_field :manufacturer, maxlength: 20 %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :car_model %>
      <%= f.text_field :car_model, maxlength: 50 %>
    </div>
     <div class="form-group col-md-6">
      <%= f.label :year %>
      <%= f.text_field :year, maxlength: 4 %>
    </div>
     <div class="form-group col-md-6">
      <%= f.label :capacity %>
      <%= f.text_field :capacity, maxlength: 10 %>
    </div>
     <div class="form-group col-md-6">
      <%= f.label :type_fuel_id %>
      <%= f.collection_select(:type_fuel_id, @fuel_registers, :id, :type_fuel, { prompt: "Choose a Fuel Type" }) %>
    </div>
      <div class="form-group col-md-6">
      <%= f.label :reported_consumption %>
      <%= f.text_field :reported_consumption, maxlength: 10 %>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Cadastrar</button>
<% end %>

app/views/car_manufacturers/edit.html.erb
<h1>Editing Car Manufacturer</h1>

<%= render 'form', car_manufacturer: @car_manufacturer %>

<%= link_to t('Back'), car_manufacturers_path %>

app/views/car_manufacturers/index.html.erb
<h1>Car Manufacturer</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Car Model </th>
      <th>Year </th>
      <th>Capacity</th>
      <th>Type Fuel</th>
      <th> Reported Consumption</th>
    </tr>
  </thead>

  <tbody>
    <% @car_manufacturer.each do |f| %>      
      <tr>
        <td><%=f.manufacturer %></td>
        <td><%=f.car_model %></td>
        <td><%=f.year%></td>
        <td><%=f.capacity%></td>
        <td><%=f.type_fuel_id%></td>
        <td><%=f.reported_consumption%></td>
          <td> 
          <%= link_to t('links.Edit'), edit_car_manufacturer_path(f) %>
          <%= link_to t('links.Destroy'), f, method: :delete, data: { confirm: ('Vocẽ tem certeza?') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Car Model', new_car_manufacturer_path, class: 'btn btn-primary' %>

app/views/car_manufacturers/new.html.erb
<h1>car_manufacturer new</h1>

<%= render 'form', car_manufacturer: @car_manufacturer %>

app/views/car_manufacturers/show.html.erb
<h1>Detalhes do Fabricante e Modelo</h1>

<p>
  Tipo de Combustível: <%= @car_manufacturer.manufacturer %><br>
  Valor por Litro: <%= @car_manufacturer.car_model %>
</p>

<%= link_to 'Editar', edit_car_manufacturer_path(@car_manufacturer) %> |
<%= link_to 'Voltar', car_manufacturers_path %>

app/views/fuel_registers/_form.html.erb
<%= form_for(@fuel_register) do |f| %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :type_fuel %>
      <%= f.text_field :type_fuel, maxlength: 100 %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :value_liter %>
      <%= f.text_field :value_liter, maxlength: 100 %>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Cadastrar</button>
<% end %>

app/views/fuel_registers/edit.html.erb
<h1>Editing Fuel Type</h1>

<%= render 'form', fuel_register: @fuel_register %>

<%= link_to t('Back'), fuel_registers_path %>

app/views/fuel_registers/index.html.erb
<h1>Fuel Register</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    <% @fuel_register.each do |f| %>      
      <tr>
        <td><%= f.type_fuel %></td>
        <td><%= f.value_liter %></td>
          <td> 
          <%= link_to t('links.Edit'), edit_fuel_register_path(f) %>
          <%= link_to t('links.Destroy'), f, method: :delete, data: { confirm: ('Vocẽ tem certeza?') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Combustivel', new_fuel_register_path, class: 'btn btn-primary' %>

app/views/fuel_registers/new.html.erb
<h1>fuel_register new</h1>

<%= render 'form', fuel_register: @fuel_register %>

app/views/fuel_registers/show.html.erb
<h1>Detalhes do Tipo de Combustível</h1>

<p>
  Tipo de Combustível: <%= @fuel_register.type_fuel %><br>
  Valor por Litro: <%= @fuel_register.value_liter %>
</p>

<%= link_to 'Editar', edit_fuel_register_path(@fuel_register) %> |
<%= link_to 'Voltar', fuel_registers_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p></p>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>    
    <div class="alert alert-success alert-dismissible fade show" role="alert">
         <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<%end%>

<% if alert.present? %>    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
   <p>Developed by Anderson Pinheiro - Ruby On Rails</p>
     <p>
    </p>

</footer>

app/views/layouts/_topnavbar.html.erb
<div class="container">
  <header class="blog-header py-3">

    </div>
  </header>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EconoDrive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

   <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <%= render 'layouts/topnavbar'%>
    <main class="container">

     <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>
     <%= render 'layouts/footer'%>
  </body>
</html>